# Generated by Django 3.0.5 on 2023-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('low end device', 'low end device'), ('mid range device', 'mid range device'), ('top end model', 'top end model'), ('flagship', 'flagship')], max_length=50),
        ),
    ]
